
openapi: 3.0.0

info:
  title: My first open api
  contact:
    name: Timur Akhounov
    email: timon1983@yandex.ru
  version: 1.0.0
servers:
  - url: http://localhost:8088
    description: Enter point
paths:
  /api/user/list:
    post:
      tags:
        - user-controller
      operationId: listOfUsers
      requestBody:
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
  /api/car/{id}:
    post:
      tags:
        - car-controller
      operationId: carById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Car'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        age:
          type: integer
          format: int32
        isActive:
          type: boolean
    Car:
      type: object
      properties:
        id:
          type: integer
          format: int32
        model:
          type: string
        color:
          type: string
        user:
          $ref: '#/components/schemas/User'